### ISSUE TITLE
Create a blog on the LDES website

### ISSUE THREAD

**Issue by pietercolpaert** [TREEcg/site#5]
We want to create a blog on the LDES website to share stories and ideas with LDES. The sky is the limit, but let’s have different people doing guest blog posts

Template could look something like this:

`_posts/{date}-{post-slug}.md`:

```markdown
---
title: A post about LDES!
#webid will fetch the name and display picture from the profile and display it?
webid: https://pietercolpaert.be/#me
shortdescription: LDES is awesome because it...
previewimage: img/logo-ldes.svg
---

## Just some markdown

```

TODO:
 * [x] Make sure there’s a nice preview in LinkedIn/Twitter/Mastodon/Search Engines/... By annotating the post page itself with rich snippets
 * [x] Fetch the WebID profile information when building the page

**Comment by ajuvercr** [comment]
Right, didn't see the issue.
Pr #7 is a subset of this issue which is a MVP to get blog posts working.
